############# English navigation ##############

# main menu
[[main]]
name = "Learn More"
weight = 1

[[main]]
parent = "Learn More"
name = "How does it work?"
pageRef = "/how-does-it-work"
weight = 1

[[main]]
parent = "Learn More"
name = "Devices"
pageRef = "/devices"
weight = 5

[[main]]
name = "Team"
pageRef = "/team"
weight = 2

# [[main]]
# name = "Elements"
# pageRef = "/elements"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# pageRef = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# pageRef = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# pageRef = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# pageRef = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# pageRef = "/404"


# footer menu

# [[footer]]
# name = "About"
# pageRef = "/about"
# weight = 1

# [[footer]]
# name = "Elements"
# pageRef = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# pageRef = "/privacy-policy"
# weight = 3
